package com.github.carobatata.currencyconverter.ui.model

import androidx.annotation.DrawableRes
import com.github.carobatata.currencyconverter.R

enum class Currency(
    val code: String,
    val fullName: String,
    @DrawableRes val flagRes: Int? = null
) {
    USD("USD", "United States Dollar", R.drawable.flag_us),
    AED("AED", "United Arab Emirates Dirham", R.drawable.flag_ae),
    AFN("AFN", "Afghan Afghani", R.drawable.flag_af),
    ALL("ALL", "Albanian Lek", R.drawable.flag_al),
    AMD("AMD", "Armenian Dram", R.drawable.flag_am),
    ANG("ANG", "Netherlands Antillean Guilder", R.drawable.flag_an),
    AOA("AOA", "Angolan Kwanza", R.drawable.flag_ao),
    ARS("ARS", "Argentine Peso", R.drawable.flag_ar),
    AUD("AUD", "Australian Dollar", R.drawable.flag_au),
    AWG("AWG", "Aruban Florin", R.drawable.flag_aw),
    AZN("AZN", "Azerbaijani Manat", R.drawable.flag_az),
    BAM("BAM", "Bosnia-Herzegovina Convertible Mark", R.drawable.flag_ba),
    BBD("BBD", "Barbadian Dollar", R.drawable.flag_bb),
    BDT("BDT", "Bangladeshi Taka", R.drawable.flag_bd),
    BGN("BGN", "Bulgarian Lev", R.drawable.flag_bg),
    BHD("BHD", "Bahraini Dinar", R.drawable.flag_bh),
    BIF("BIF", "Burundian Franc", R.drawable.flag_bi),
    BMD("BMD", "Bermudian Dollar", R.drawable.flag_bm),
    BND("BND", "Brunei Dollar", R.drawable.flag_bn),
    BOB("BOB", "Bolivian Boliviano", R.drawable.flag_bo),
    BRL("BRL", "Brazilian Real", R.drawable.flag_br),
    BSD("BSD", "Bahamian Dollar", R.drawable.flag_bs),
    BTN("BTN", "Bhutanese Ngultrum", R.drawable.flag_bt),
    BWP("BWP", "Botswana Pula", R.drawable.flag_bw),
    BYN("BYN", "Belarusian Ruble", R.drawable.flag_by),
    BZD("BZD", "Belize Dollar", R.drawable.flag_bz),
    CAD("CAD", "Canadian Dollar", R.drawable.flag_ca),
    CDF("CDF", "Congolese Franc", R.drawable.flag_cd),
    CHF("CHF", "Swiss Franc", R.drawable.flag_ch),
    CLF("CLF", "Chilean Unit of Account (UF)", R.drawable.flag_cl),
    CLP("CLP", "Chilean Peso", R.drawable.flag_cl),
    CNH("CNH", "Chinese Yuan (Offshore)", R.drawable.flag_cn),
    CNY("CNY", "Chinese Yuan", R.drawable.flag_cn),
    COP("COP", "Colombian Peso", R.drawable.flag_co),
    CRC("CRC", "Costa Rican Colón", R.drawable.flag_cr),
    CUP("CUP", "Cuban Peso", R.drawable.flag_cu),
    CVE("CVE", "Cape Verdean Escudo", R.drawable.flag_cv),
    CZK("CZK", "Czech Koruna", R.drawable.flag_cz),
    DJF("DJF", "Djiboutian Franc", R.drawable.flag_dj),
    DKK("DKK", "Danish Krone", R.drawable.flag_dk),
    DOP("DOP", "Dominican Peso", R.drawable.flag_do),
    DZD("DZD", "Algerian Dinar", R.drawable.flag_dz),
    EGP("EGP", "Egyptian Pound", R.drawable.flag_eg),
    ERN("ERN", "Eritrean Nakfa", R.drawable.flag_er),
    ETB("ETB", "Ethiopian Birr", R.drawable.flag_et),
    EUR("EUR", "Euro", R.drawable.flag_eu),
    FJD("FJD", "Fijian Dollar", R.drawable.flag_fj),
    FKP("FKP", "Falkland Islands Pound", R.drawable.flag_fk),
    FOK("FOK", "Faroese Króna", R.drawable.flag_fo),
    GBP("GBP", "British Pound Sterling", R.drawable.flag_gb),
    GEL("GEL", "Georgian Lari", R.drawable.flag_ge),
    GGP("GGP", "Guernsey Pound", R.drawable.flag_gg),
    GHS("GHS", "Ghanaian Cedi", R.drawable.flag_gh),
    GIP("GIP", "Gibraltar Pound", R.drawable.flag_gi),
    GMD("GMD", "Gambian Dalasi", R.drawable.flag_gm),
    GNF("GNF", "Guinean Franc", R.drawable.flag_gn),
    GTQ("GTQ", "Guatemalan Quetzal", R.drawable.flag_gt),
    GYD("GYD", "Guyanese Dollar", R.drawable.flag_gy),
    HKD("HKD", "Hong Kong Dollar", R.drawable.flag_hk),
    HNL("HNL", "Honduran Lempira", R.drawable.flag_hn),
    HRK("HRK", "Croatian Kuna", R.drawable.flag_hr),
    HTG("HTG", "Haitian Gourde", R.drawable.flag_ht),
    HUF("HUF", "Hungarian Forint", R.drawable.flag_hu),
    IDR("IDR", "Indonesian Rupiah", R.drawable.flag_id),
    ILS("ILS", "Israeli New Shekel", R.drawable.flag_il),
    IMP("IMP", "Isle of Man Pound", R.drawable.flag_im),
    INR("INR", "Indian Rupee", R.drawable.flag_in),
    IQD("IQD", "Iraqi Dinar", R.drawable.flag_iq),
    IRR("IRR", "Iranian Rial", R.drawable.flag_ir),
    ISK("ISK", "Icelandic Krona", R.drawable.flag_is),
    JEP("JEP", "Jersey Pound", R.drawable.flag_je),
    JMD("JMD", "Jamaican Dollar", R.drawable.flag_jm),
    JOD("JOD", "Jordanian Dinar", R.drawable.flag_jo),
    JPY("JPY", "Japanese Yen", R.drawable.flag_jp),
    KES("KES", "Kenyan Shilling", R.drawable.flag_ke),
    KGS("KGS", "Kyrgyzstani Som", R.drawable.flag_kg),
    KHR("KHR", "Cambodian Riel", R.drawable.flag_kh),
    KID("KID", "Kiribati Dollar", R.drawable.flag_ki),
    KMF("KMF", "Comorian Franc", R.drawable.flag_km),
    KRW("KRW", "South Korean Won", R.drawable.flag_kr),
    KWD("KWD", "Kuwaiti Dinar", R.drawable.flag_kw),
    KYD("KYD", "Cayman Islands Dollar", R.drawable.flag_ky),
    KZT("KZT", "Kazakhstani Tenge", R.drawable.flag_kz),
    LAK("LAK", "Lao Kip", R.drawable.flag_la),
    LBP("LBP", "Lebanese Pound", R.drawable.flag_lb),
    LKR("LKR", "Sri Lankan Rupee", R.drawable.flag_lk),
    LRD("LRD", "Liberian Dollar", R.drawable.flag_lr),
    LSL("LSL", "Lesotho Loti", R.drawable.flag_ls),
    LYD("LYD", "Libyan Dinar", R.drawable.flag_ly),
    MAD("MAD", "Moroccan Dirham", R.drawable.flag_ma),
    MDL("MDL", "Moldovan Leu", R.drawable.flag_md),
    MGA("MGA", "Malagasy Ariary", R.drawable.flag_mg),
    MKD("MKD", "Macedonian Denar", R.drawable.flag_mk),
    MMK("MMK", "Myanmar Kyat", R.drawable.flag_mm),
    MNT("MNT", "Mongolian Tögrög", R.drawable.flag_mn),
    MOP("MOP", "Macanese Pataca", R.drawable.flag_mo),
    MRU("MRU", "Mauritanian Ouguiya", R.drawable.flag_mr),
    MUR("MUR", "Mauritian Rupee", R.drawable.flag_mu),
    MVR("MVR", "Maldivian Rufiyaa", R.drawable.flag_mv),
    MWK("MWK", "Malawian Kwacha", R.drawable.flag_mw),
    MXN("MXN", "Mexican Peso", R.drawable.flag_mx),
    MYR("MYR", "Malaysian Ringgit", R.drawable.flag_my),
    MZN("MZN", "Mozambican Metical", R.drawable.flag_mz),
    NAD("NAD", "Namibian Dollar", R.drawable.flag_na),
    NGN("NGN", "Nigerian Naira", R.drawable.flag_ng),
    NIO("NIO", "Nicaraguan Córdoba", R.drawable.flag_ni),
    NOK("NOK", "Norwegian Krone", R.drawable.flag_no),
    NPR("NPR", "Nepalese Rupee", R.drawable.flag_np),
    NZD("NZD", "New Zealand Dollar", R.drawable.flag_nz),
    OMR("OMR", "Omani Rial", R.drawable.flag_om),
    PAB("PAB", "Panamanian Balboa", R.drawable.flag_pa),
    PEN("PEN", "Peruvian Sol", R.drawable.flag_pe),
    PGK("PGK", "Papua New Guinean Kina", R.drawable.flag_pg),
    PHP("PHP", "Philippine Peso", R.drawable.flag_ph),
    PKR("PKR", "Pakistani Rupee", R.drawable.flag_pk),
    PLN("PLN", "Polish Zloty", R.drawable.flag_pl),
    PYG("PYG", "Paraguayan Guaraní", R.drawable.flag_py),
    QAR("QAR", "Qatari Riyal", R.drawable.flag_qa),
    RON("RON", "Romanian Leu", R.drawable.flag_ro),
    RSD("RSD", "Serbian Dinar", R.drawable.flag_rs),
    RUB("RUB", "Russian Ruble", R.drawable.flag_ru),
    RWF("RWF", "Rwandan Franc", R.drawable.flag_rw),
    SAR("SAR", "Saudi Riyal", R.drawable.flag_sa),
    SBD("SBD", "Solomon Islands Dollar", R.drawable.flag_sb),
    SCR("SCR", "Seychellois Rupee", R.drawable.flag_sc),
    SDG("SDG", "Sudanese Pound", R.drawable.flag_sd),
    SEK("SEK", "Swedish Krona", R.drawable.flag_se),
    SGD("SGD", "Singapore Dollar", R.drawable.flag_sg),
    SHP("SHP", "Saint Helena Pound", R.drawable.flag_sh),
    SLE("SLE", "Sierra Leonean Leone", R.drawable.flag_sl),
    SLL("SLL", "Sierra Leonean Leone", R.drawable.flag_sl),
    SOS("SOS", "Somali Shilling", R.drawable.flag_so),
    SRD("SRD", "Surinamese Dollar", R.drawable.flag_sr),
    SSP("SSP", "South Sudanese Pound", R.drawable.flag_ss),
    STN("STN", "São Tomé and Príncipe Dobra", R.drawable.flag_st),
    SYP("SYP", "Syrian Pound", R.drawable.flag_sy),
    SZL("SZL", "Swazi Lilangeni", R.drawable.flag_sz),
    THB("THB", "Thai Baht", R.drawable.flag_th),
    TJS("TJS", "Tajikistani Somoni", R.drawable.flag_tj),
    TMT("TMT", "Turkmenistan Manat", R.drawable.flag_tm),
    TND("TND", "Tunisian Dinar", R.drawable.flag_tn),
    TOP("TOP", "Tongan Paʻanga", R.drawable.flag_to),
    TRY("TRY", "Turkish Lira", R.drawable.flag_tr),
    TTD("TTD", "Trinidad and Tobago Dollar", R.drawable.flag_tt),
    TVD("TVD", "Tuvalu Dollar", R.drawable.flag_tv),
    TWD("TWD", "New Taiwan Dollar", R.drawable.flag_tw),
    TZS("TZS", "Tanzanian Shilling", R.drawable.flag_tz),
    UAH("UAH", "Ukrainian Hryvnia", R.drawable.flag_ua),
    UGX("UGX", "Ugandan Shilling", R.drawable.flag_ug),
    UYU("UYU", "Uruguayan Peso", R.drawable.flag_uy),
    UZS("UZS", "Uzbekistani Som", R.drawable.flag_uz),
    VES("VES", "Venezuelan Bolívar", R.drawable.flag_ve),
    VND("VND", "Vietnamese Dong", R.drawable.flag_vn),
    VUV("VUV", "Vanuatu Vatu", R.drawable.flag_vu),
    WST("WST", "Samoan Tālā", R.drawable.flag_ws),
    XAF("XAF", "Central African CFA franc", R.drawable.flag_cm),
    XCD("XCD", "East Caribbean Dollar", R.drawable.flag_ag),
    XCG("XCG", "Other Currency", R.drawable.flag_xc),
    XDR("XDR", "IMF Special Drawing Rights", R.drawable.flag_xd),
    XOF("XOF", "West African CFA franc", R.drawable.flag_sn),
    XPF("XPF", "CFP franc", R.drawable.flag_nc),
    YER("YER", "Yemeni Rial", R.drawable.flag_ye),
    ZAR("ZAR", "South African Rand", R.drawable.flag_za),
    ZMW("ZMW", "Zambian Kwacha", R.drawable.flag_zm),
    ZWG("ZWG", "Other Currency", R.drawable.flag_zw),
    ZWL("ZWL", "Zimbabwean Dollar", R.drawable.flag_zw)
}
